services:
  - type: web
    name: dromominds
    runtime: docker
    plan: free
    region: singapore
    repo: https://github.com/moktarul12/dromominds
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeployTrigger: commit
